com/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    path('register/', account_views.register, name='register'),
    path('profile/', account_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from store import views

app_name ='core'
urlpatterns = [
    path('',views.home_view, name='home'),
    path('product_detail/<int:pk>', views.product_detail, name="product_detail"),
    path('cart', views.cart, name="cart"),
    path('checkout', views.checkout_summary, name="checkout")

]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.shortcuts import reverse
from accounts.models import Agent , Customer 
from .utils import unique_transaction_id_generator
from django.db.models.signals import pre_save
from django.conf import settings
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name



class Products(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=100)
    image = models.ImageField(verbose_name='Product_Image',upload_to='img/products', null=True, blank=True)
    price = models.FloatField()
    description = models.TextField()
    updated_at = models.DateTimeField(auto_now=True,)
    created_at = models.DateTimeField(auto_now_add=True)
   
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core:product_detail', kwargs={'pk':self.id})
   
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    

class Order(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    agent = models.ForeignKey(Agent, on_delete=models.SET_NULL, null=True,blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=100, blank=True)
    billing_address = models.ForeignKey('ShippingAddress',on_delete=models.SET_NULL, blank=True, null=True)
    completed = models.BooleanField(default=False, null=True, blank=False)
    order_reviewed = models.BooleanField(default=False, null=True, blank=False)



    def __str__(self):
        return self.customer.email

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


    @classmethod
    def pre_save_create_order_id(self,sender, instance, *args, **kwargs):
        if not instance.transaction_id:
            instance.transaction_id= unique_transaction_id_generator(instance)


pre_save.connect(Order.pre_save_create_order_id, sender=Order)

class OrderItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total 
class ShippingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200,verbose_name="Address")
    apartment_address = models.CharField(max_length=200, verbose_name="Address 2", blank=True)

    def __str__(self):
        return self.user







         


    
    

store/views.py
from django.shortcuts import render , get_object_or_404 
from .models import *

# Create your views here.
def home_view(request):
    products = Products.objects.all()
    categories = Category.objects.all()
    context = {'products':products,'categories':categories}
    return render(request, 'store/index.html', context)


def product_detail(request, pk):
    product = get_object_or_404(Products, pk=pk)
    context = {'product':product}
    return render(request, 'store/product-page.html', context)

def cart(request):
    if request.user.is_authenticated:
        customer = request.user
        order, create = Order.objects.get_or_create(customer=customer, completed=False)
        items = order.orderitem_set.all()
    else:
        items =[]
    context = {'items':items, 'order':order}
    return render(request, 'store/cart.html', context)



def checkout_summary(request):
    if request.user.is_authenticated:
        customer = request.user
        order, create = Order.objects.get_or_create(customer=customer, completed=False)
        items = order.orderitem_set.all()
    else:
        items =[]
    context = {'items':items, 'order':order}
    return render(request, 'store/checkout-page.html', context)

templates/store/cart.html
{% extends 'base.html' %}

{%  %}


{% block content %}

{% include 'components/nav.html' %}
<div class="mt-70">
  <div class="d-flex align-items-center h-100">
    <div class="container text-center py-5">
    
    </div>
  </div>
</div>

<main>
  <div class="container">
      <a
    href="#"
    class="btn btn-primary btn-lg"
    tabindex="-1"
    role="button"
    aria-disabled="true"
    >Back to Shoping</a>


    <!--Section: Block Content-->
    <section class="mt-5 mb-4">

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-lg-8">

          <!-- Card -->
          <div class="card wish-list mb-4">
            <div class="card-body">

              <h5 class="mb-4">Cart (<span> {{order.get_cart_items|floatformat:2}}</span> items)</h5>

            {% for item in items%}

              <div class="row mb-4">
                <div class="col-md-5 col-lg-3 col-xl-3">
                  <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                    <img class="img-fluid w-100" src="{{ item.product.imageURL}}" alt="Sample">
                    <a href="#!">
                      <div class="mask waves-effect waves-light">
                        <img class="img-fluid w-100" src="{{ item.product.imageURL}}">
                        <div class="mask rgba-black-slight waves-effect waves-light"></div>
                      </div>
                    </a>
                  </div>
                </div>
                <div class="col-md-7 col-lg-9 col-xl-9">
                  <div>
                    <div class="d-flex justify-content-between">
                      <div>
                        <h5>{{ item.product.name }}</h5>
                      </div>
                      <div>
                        <div class="def-number-input number-input safari_only mb-0 w-100">
                          <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" class="minus">-</button>
                          <input class="quantity" min="0" name="quantity" value="{{ item.quantity }}" type="number">
                          <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="plus">+</button>
                        </div>
                        <small id="passwordHelpBlock" class="form-text text-muted text-center">
                          (Note, {{ item.quantity }} piece)
                        </small>
                      </div>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <a href="#!" type="button" class="card-link-secondary small text-uppercase mr-3"><i class="fas fa-trash-alt mr-1"></i> Remove item </a>
                     
                      </div>
                      <p class="mb-0"><span><strong>N{{ item.get_total |floatformat:2}}</strong></span></p>
                    </div>
                  </div>
                </div>
              </div>

              <hr class="mb-4">
              {% endfor %}
              <!-- <div class="row mb-4">
                <div class="col-md-5 col-lg-3 col-xl-3">
                  <div class="view zoom overlay z-depth-1 rounded mb-3 mb-md-0">
                    <img class="img-fluid w-100" src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13a.jpg" alt="Sample">
                    <a href="#!">
                      <div class="mask waves-effect waves-light">
                        <img class="img-fluid w-100" src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/13.jpg">
                        <div class="mask rgba-black-slight waves-effect waves-light"></div>
                      </div>
                    </a>
                  </div>
                </div>
                <div class="col-md-7 col-lg-9 col-xl-9">
                  <div>
                    <div class="d-flex justify-content-between">
                      <div>
                        <h5>Red hoodie</h5>
                        <p class="mb-3 text-muted text-uppercase small">Hoodie - red</p>
                        <p class="mb-2 text-muted text-uppercase small">Color: red</p>
                        <p class="mb-3 text-muted text-uppercase small">Size: M</p>
                      </div>
                      <div>
                        <div class="def-number-input number-input safari_only mb-0 w-100">
                          <button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" class="minus"></button>
                          <input class="quantity" min="0" name="quantity" value="1" type="number">
                          <button onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="plus"></button>
                        </div>
                      </div>
                    </div>
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <a href="#!" type="button" class="card-link-secondary small text-uppercase mr-3"><i class="fas fa-trash-alt mr-1"></i> Remove item </a>
                        <a href="#!" type="button" class="card-link-secondary small text-uppercase"><i class="fas fa-heart mr-1"></i> Move to wish list </a>
                      </div>
                      <p class="mb-0"><span><strong>$35.99</strong></span></p>
                    </div>
                  </div>
                </div>
              </div> -->
              <p class="text-primary mb-0"><i class="fas fa-info-circle mr-1"></i>Process Your Order and Only Pay On Delivery.</p>

            </div>
          </div>
          <!-- Card -->

          <!-- Card -->
          <!-- <div class="card mb-4">
            <div class="card-body">

              <h5 class="mb-4">Expected shipping delivery</h5>

              <p class="mb-0"> Thu., 12.03. - Mon., 16.03.</p>
            </div>
          </div> -->
          <!-- Card -->

          <!-- Card -->
          <!-- <div class="card mb-4">
            <div class="card-body">

              <h5 class="mb-4">We accept</h5>

              <img class="mr-2" width="45px" src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg" alt="Visa">
              <img class="mr-2" width="45px" src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg" alt="American Express">
              <img class="mr-2" width="45px" src="https://mdbootstrap.com/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg" alt="Mastercard">
              <img class="mr-2" width="45px" src="https://z9t4u9f6.stackpathcdn.com/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.png" alt="PayPal acceptance mark">
            </div>
          </div> -->
          <!-- Card -->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4">

          <!-- Card -->
          <div class="card mb-4">
            <div class="card-body">

              <h5 class="mb-3">The total amount of</h5>

              <ul class="list-group list-group-flush">
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                  Temporary amount
                  <span>N{{ order.get_cart_total }}</span>
                </li>
                <!-- <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                  Shipping
                  <span>Gratis</span>
                </li> -->
                <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                  <div>
                    <strong>The total amount of</strong>
                    <strong>
                      <p class="mb-0">(including VAT)</p>
                    </strong>
                  </div>
                  <span><strong>N{{ order.get_cart_total }}</strong></span>
                </li>
           
              </ul>

              <button type="button" class="btn btn-primary btn-block waves-effect waves-light"> 
                <a href="{% url 'core:checkout' %}">Proceed to checkout</a></button>

            </div>
          </div>
          <!-- Card -->

          <!-- Card -->
          <!-- <div class="card mb-4">
            <div class="card-body">

              <a class="dark-grey-text d-flex justify-content-between" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Add a discount code (optional)
                <span><i class="fas fa-chevron-down pt-1"></i></span>
              </a>

              <div class="collapse" id="collapseExample">

              </div>
            </div>
          </div> -->
          <!-- Card -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </section>
    <!--Section: Block Content-->

  </div>
</main>

{% endblock %}

templates/store/checkout-page.html
{% extends 'base.html' %}


{% block content %}

{% include 'components/nav.html' %}



  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card content-->
            <form class="card-body">

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--firstName-->
                  <div class="md-form ">
                    <input type="text" id="firstName" class="form-control">
                    <label for="firstName" class="">First name</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    <input type="text" id="lastName" class="form-control">
                    <label for="lastName" class="">Last name</label>
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <!--Username-->
              <div class="md-form input-group pl-0 mb-5">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="basic-addon1">@</span>
                </div>
                <input type="text" class="form-control py-0" placeholder="Username" aria-describedby="basic-addon1">
              </div>

              <!--email-->
              <div class="md-form mb-5">
                <input type="text" id="email" class="form-control" placeholder="youremail@example.com">
                <label for="email" class="">Email (optional)</label>
              </div>

              <!--address-->
              <div class="md-form mb-5">
                <input type="text" id="address" class="form-control" placeholder="1234 Main St">
                <label for="address" class="">Address</label>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
   
                <!--Grid column-->

            

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
          {% for item in items %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ item.product.name }}</h6>
                
              </div>
              <span class="text-muted">N{{ item.product.price|floatformat:2 }}</span>
            </li>
          {% endfor %}

            <li class="list-group-item d-flex justify-content-between">
              <span>Total (NAIRA)</span>
              <strong>N{{ order.get_cart_total }}</strong>
            </li>
          </ul>
          <!-- Cart -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  {% include 'components/footer.html' %}

{% endblock %}

templates/store/index.html
{% extends 'base.html' %}


{% block content %}

{% include 'components/nav.html' %}

{% include 'components/carousel.html' %}



  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
    
    
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% for items in categories %}
            <li class="nav-item">
              <a class="nav-link" href="#">{{ items.name}}</a>
            </li>
            {% endfor %}
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      
      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for items in products %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
          
            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{ items.imageURL }}" class="card-img-top"
                  alt="">
                <a href="{{items.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->
          
              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{items.get_absolute_url}}" class="grey-text">
                  <h5>{{ items.name }}</h5>
                </a>
                
                <h5>
                  <strong>
                    <a href="{{ items.get_absolute_url }}" class="dark-grey-text">{{ items.category.name}}
                      <!-- <span class="badge badge-pill danger-color">NEW</span> -->
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>{{ items.price|floatformat:2 }}N</strong>
                </h4>

              </div>
              <!--Card content-->
              <button type="button" data-product={{items.id}} data-action="add" class="btn btn-outline-info btn-rounded update-cart" data-mdb-ripple-color="dark">Add to cart</button>
            </div>
            <!--Card-->
       
          

          </div>
          <!--Grid column-->
          {% endfor %}



        </div>
        <!--Grid row-->

      

      </section>
      
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->




  {% include 'components/footer.html' %}

{% endblock %}

templates/store/product-page.html
{% extends 'base.html' %}


{% block content %}

{% include 'components/nav.html' %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ product.imageURL }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ product.category.name }}</span>
              </a>
              <!-- <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a> -->
            </div>

            <p class="lead">
              <!-- <span class="mr-1">
                <del>$200</del>
              </span> -->
              <span>N{{ product.price|floatformat:2}}</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ product.description}}</p>

            <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

  

    </div>
  </main>
  <!--Main layout-->

 
  {% include 'components/footer.html' %}

{% endblock %}